### PR TITLE
lestarch: command raw text input and fixed client validation

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| OWLS |
|**_Affected Component_**| Validation |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Adds in much better validation, error handling, and error reporting.  Provides a raw command input that syncs with the selected command input for copy/past in and out of commands.

### CODE REVIEW

**Comment by metzdigital** [comment]
It would be nice if it "auto-capitalize" text submitted:
image

**Comment by metzdigital** [comment]
A bug found, it appears `0` is not seen as a valid integer argument:
image

**Comment by metzdigital** [comment]
I'm not sure how much this matters, but I noticed there is no "auto-casing" for the command, just the arguments:
image

**Comment by metzdigital** [comment]
An interesting behavior I noticed. For the ADC_ADS1119_TESTING command arg1 thru arg3 are labeled as U32:
```
<command kind="guarded" opcode="0" mnemonic="ADC_ADS1119_TESTING">
	<comment>
		Command to run tests against ADS1119 driver
	</comment>
	<args>
		<arg type="Backplane::BpHwTestNames" name="test"> </arg>
		<arg type="U32" name="arg1"> </arg>
		<arg type="U32" name="arg2"> </arg>
		<arg type="U32" name="arg3"> </arg>
		<arg type="F32" name="arg4"> </arg>
	</args>
</command>
```
But values larger than 4294967295 still get the "green check":
image
Until I attempt to send the command:
image

**Comment by metzdigital** [comment]
This isn't the most descriptive error, the real issue is too long of a string:
image

**Comment by metzdigital** [comment]
The above items is all I could find when doing extensive hammering on it. Really well done @LeStarch!

**Comment by LeStarch** [comment]
@metzdigital the zero not an int error is a true error, and I will fix it.  I look into the out-of-range error with the other....I can probably set limits, maybe, probably.

**Comment by metzdigital** [comment]
Verified above items have been fixed

**Review by metzdigital — APPROVED** [review]
Approved.

**Pull request merged**
