### PR TITLE
Update/fancy tab

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

A description of the changes contained in the PR.

## Rationale

A rationale for this change. e.g. fixes bug, or most projects need XYZ feature.

## Testing/Review Recommendations

Fill in testing procedures, specific items to focus on for review, or other info to help the team verify these changes are flight-quality.

## Future Work

Note any additional work that will be done relating to this issue.

### CODE REVIEW

**Comment by LeStarch** [comment]
Python alert is not new, just tabbed in one.

**Comment by metzdigital** [comment]
this is so cool!

**Comment by metzdigital** [comment]
@LeStarch I believe you said you were going to fix these, given I'm running an older version of python3:
image

Which I'm guessing is why I get this:
image

**Comment by LeStarch** [comment]
@metzdigital should work on your revision now.

**Comment by metzdigital** [comment]
* Confirmed the python error has gone away and now get multiline error reporting. 
 * Note bug found when dealing with what looks like the smart highlighting:
image
 * Will still approve to get this merged but should be fixed at some point.

**Review by metzdigital — DISMISSED** [review]
Approved.

**Review by metzdigital — APPROVED** [review]
Approved.

**Comment by LeStarch** [comment]
Merging this change.  Lint warnings are not new (just moved slightly) and

**Pull request merged**
