### PR TITLE
Replace LGTM with Github Actions

### PR DESCRIPTION
**Pull request by thomas-bc**
| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**| GitHub Actions |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Adds a Github Actions workflow that runs the security and quality static code analysis in order to phase LGTM out.

## Rationale

[lgtm.com](https://github.com/nasa/fprime/pull/lgtm.com) will be shut down at the end of the year.

## Future Work

Remove the LGTM configuration files once we're ok with phasing it out.

## Comments

Results should be viewable once the checks are done. It's currently running all queries from the security-and-quality suite, let me know if we want to filter some categories out.

### CODE REVIEW

**Review by LeStarch — DISMISSED** [review]
The changes look good, however; we might fix the breakages. @thomas-bc do you want to do that in this PR, or a separate one?

**Comment by thomas-bc** [comment]
I implemented the recommended way of dealing with the `Uncontrolled data used in path expression` [alerts](https://github.com/fprime-community/fprime-gds/security/code-scanning/2). Let me know what you think. It's using [normpath()](https://docs.python.org/3/library/os.path.html#os.path.normpath) to normalize the path (i.e. resolve special instructions like `../` etc...) and check that the requested resource is within logdir.

The two `Wrong number of arguments in a call` [alerts](https://github.com/fprime-community/fprime-gds/security/code-scanning/15) seem to be expected in both cases, so we should probably dismiss those alerts. One has the LGTM suppression flag, the other one is a test case testing the raising of an exception.

**Comment by LeStarch** [comment]
@thomas-bc looks good to me.  Can we suppress-by-comment or is there some other way to do it?  Regardless, I agree with the proposed path-forward.

**Review by LeStarch — APPROVED** [review]
@thomas-bc approved!

**Pull request merged**
